name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
    tags:
      - "v*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag wxwmatt/ubuntu-gear:${{ github.ref_name }}
