name: Docker Image CI
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set tag
        run: |
          echo "TAG=${{ github.ref_name }}" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            wxwmatt/ubuntu-gear:${{ env.TAG }}
            wxwmatt/ubuntu-gear:latest

      - name: Build and push (zsh)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile-zsh
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            wxwmatt/ubuntu-gear-zsh:${{ env.TAG }}
            wxwmatt/ubuntu-gear-zsh:latest
